services:
  - type: web
    name: devverse
    runtime: node
    plan: standard
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: B2_ENDPOINT
        sync: false
      - key: B2_KEY_ID
        sync: false
      - key: B2_APPLICATION_KEY
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        value: DevVerse
      - key: ADMIN_BOOTSTRAP_TOKEN
        generateValue: true
